# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongoid-flags"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thiago Jackiw"]
  s.date = "2012-11-22"
  s.description = "Simple document flagging system for Mongoid"
  s.email = "tjackiw@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/mongoid-flags.rb",
    "mongoid-flags.gemspec",
    "mongoid.yml",
    "spec/helper.rb",
    "spec/mongoid-flags_spec.rb"
  ]
  s.homepage = "http://github.com/tjackiw/mongoid-flags"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple document flagging system for Mongoid"
  s.test_files = ["spec/helper.rb", "spec/mongoid-flags_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
    else
      s.add_dependency(%q<mongoid>, ["~> 3.0.3"])
      s.add_dependency(%q<bson_ext>, ["~> 1.6"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, ["~> 2.10.0"])
    end
  else
    s.add_dependency(%q<mongoid>, ["~> 3.0.3"])
    s.add_dependency(%q<bson_ext>, ["~> 1.6"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, ["~> 2.10.0"])
  end
end

